# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/macan/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),macan)

# radio file could be needed here, for example: $(call add-radio-file-sha1-checked,radio/abl.img,fcce3598958c93c8361892237194799222141710)

endif
